# Generated by Django 3.2.2 on 2021-05-15 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_table', '0013_remove_inquiry_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='landline_num',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Number cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='mobile_num',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Number  cannot be negative')]),
        ),
    ]
