# Generated by Django 3.2.2 on 2021-05-15 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ph_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinValueValidator(0, 'Number should not be negative')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='ph_number_house',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinValueValidator(0, 'Number should not be negative')]),
        ),
    ]
