# Generated by Django 3.2.2 on 2021-05-15 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_master_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_master',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Duration cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='course_master',
            name='fees',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Fees cannot be negative')]),
        ),
    ]
