# Generated by Django 3.2.2 on 2021-05-15 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20210513_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='Amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Amount Should not be negative')]),
        ),
    ]
