# Generated by Django 3.2.2 on 2021-05-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_payment_info_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_info',
            name='receipt',
        ),
    ]
