# Generated by Django 3.2.3 on 2021-05-18 07:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0022_auto_20210515_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'], 'file extension is invalid ')])),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='admission.admission')),
            ],
        ),
    ]
